### ISSUE TITLE
When creating a letter in RP – the formatting when sending is all wrong, does not look AASI professional. 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#15]
![2018-06-05_0742.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/8a4a1ed4-facb-4c0f-a1c2-e5aff8c79986)[https://app.zenhub.com/files/136026663/66af427d-483b-4fb7-8f7a-6083e8de0250/download](https://app.zenhub.com/files/136026663/66af427d-483b-4fb7-8f7a-6083e8de0250/download)

**Comment by duchacz** [comment]
This appears to be working fine for me.
