### ISSUE TITLE
Pulled up existing proposal it is pulling in the current date not the date created BIG problem

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#19]
![2018-06-05_0756.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/2897f612-d3ad-4336-bdb6-a1658eb32ee0)

**Comment by chukon** [comment]
![2018-06-05_0801_001](https://user-images.githubusercontent.com/3256516/40977486-ba03764c-6896-11e8-895f-e0362d10bcbe.png)

**Comment by mevillarreal** [comment]
Good Morning!
Still occurring as of this morning
![image](https://user-images.githubusercontent.com/39957843/41161008-f6a95c1c-6af6-11e8-851c-a90ef015d748.png)

**Comment by mevillarreal** [comment]
Please disregard PO
![image](https://user-images.githubusercontent.com/39957843/41161080-2cfbaf9a-6af7-11e8-9bda-b99114d51dd3.png)
![image](https://user-images.githubusercontent.com/39957843/41161090-3858f302-6af7-11e8-9e03-426b60498a9e.png)

**Comment by duchacz** [comment]
I opened up proposal 49129 and it shows a date of May 2nd.  Not sure what the original date was supposed to be but I have not run into this problem with my proposals.
