### ISSUE TITLE
error in duplicating proposal

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#24]
![2018-06-05_0801.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/97d6ff28-47e7-4470-9f3b-175ac672504b)

**Comment by chukon** [comment]
From: Cynthia Borcherts 
Sent: Wednesday, May 30, 2018 11:19 AM
To: John Summers; Steven Williams; Paul Klebs; Bill Decker
Cc: Michaela Villarreal; Denise Uchacz
Subject: error in duplicating proposal

John I tried to duplicate Proposal #46390 – to 49444

Cynthia Borcherts
Sales Assistant
 
AQUA-AEROBIC SYSTEMS, INC.
6306 N. Alpine Rd.
Loves Park, IL 61111-7655
Phone: 815-639-4596 Fax: 815-654-8258
Email: cborcherts@aqua-aerobic.com
www.aqua-aerobic.com

**Comment by mevillarreal** [comment]
I was able to duplicate without error as of yesterday.
