### ISSUE TITLE
Qty is greyed out cannot enter into these fields

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#27]
![2018-06-05_0808.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/690f6a52-5391-47e7-bc14-69507785f82d)

**Comment by JSummersAqua** [comment]
Based on the screen shot, I determined that the user must have added and then deleted another part in this proposal. The Item # is 2 but the navigation bar shows 1 of 1. When I tested this by adding and deleting a part, I was able to consistently get the problem to occur. Code was added to correct this.
