### ISSUE TITLE
keyboard shortcuts for copy/paste (ctrl-C, ctrl-V) are not working

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#3]

**Comment by mevillarreal** [comment]
This function is only working in some screens - we are now able to copy/paste in the special project notes(this is a big win!), but are unable to copy/paste on the exceptions/clarifications tab, the correspondence tab, nor the schedule tab if I recall correctly

**Comment by chukon** [comment]
@mevillarreal   Please test CTRL+C, CTRL+V in exceptions/clarifications tab, the correspondence tab, and  the schedule tab

**Comment by chukon** [comment]
@duchacz   Copy/Paste has been added to proposal screen

**Comment by duchacz** [comment]
Chuck, I just logged into the development version and the copy and paste function does not work.  I should be able to highlight something, CTRL + C to copy and CTRL + V to paste and neither work. It is also not allowing me to even highlight text and right click and select "copy" from the drop down menu.  It doesn't provide a menu at all.

**Comment by mevillarreal** [comment]
The “Delete” button is also not working for us (Cynthia/I).

Backspace does, but Delete does not.

Michaela Villarreal
Sales Assistant

AQUA-AEROBIC SYSTEMS, INC.
6306 N. Alpine Rd.
Loves Park, IL 61111-7655
Ph: 815.639.4472 Fax: 815.654.8623
Email: mvillarreal@aqua-aerobic.com<mailto:mvillarreal@aqua-aerobic.com>
www.aqua-aerobic.com

**Comment by chukon** [comment]
Multiple Copy/Paste feature changes have been made in Project and Proposal Tabs.

You should be able to use the Copy (CTRL+C) and Paste (CTRL+V) commands. 
Copy/Paste & Delete Key works in Edit form of Correspondence
![image.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/d07c9889-03f4-4c63-98eb-91ca3430cbbf)

CTRL+C, CTRL+V & DELETE KEYS 
WORK IN PROPOSAL SCREEN 

![image.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/2770c111-a9a4-4c0a-8f86-aec0af1e205b)

**Comment by duchacz** [comment]
right click copy and paste work, the delete button works but the CTRL+C and CTRL+V do not work.  This seems to only be a problem on my computer (others are able to use these short cuts).

**Comment by chukon** [comment]
@duchacz I will work on this today.

**Comment by mevillarreal** [comment]
What I have noticed personally with this issue is that it works in some tabs, and does not work in others. Some tabs require the use of the drop down menu, some require the use of shortcuts. 
For example, on the first page where customer info is entered, shortcuts do not work, but the drop down menu does. In the Special Project notes tab, the drop down menu does not work, but the shortcuts do. 
This is also true for the Delete key - in the proposal tabs, the delete key works. However, in the Special Project Notes tab, it does not. Hope that makes sense.

**Comment by chukon** [comment]
@mevillarreal The shortcuts are working in all areas, correct?

**Comment by chukon** [comment]
@mevillarreal We released an update fixing the Copy/Paste/Delete & Menu Issues in the Project & Correspondence tab areas. I had Denise U. test yesterday and it was working for her. Please test and reply.

Thanks, Chuck

**Comment by chukon** [comment]
@duchacz the fields in the proposal tab for parts now have Copy/Paste abilities.

**Comment by duchacz** [comment]
This is working in RP
