### ISSUE TITLE
issue with the product code when bridging

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#33]
John,

Per our discussion, there is another issue with the product code when bridging.  Note that this is a separate issue from the one I sent the other day in regards to the master product code drop down.

You can see in the below print screen that I have manually chosen the product code for each line but when I bridged this order they changed.  Also, they didn’t just default back, part # 2600017 had always shown up as parts-aer/mix.  So for whatever reason the system is changing them to a random product code.  One was changed to Aerator, another to “multiple use”.  

![2018-06-05_0817.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/e2dfef38-6197-4817-87e8-30819e3ec415)

**Comment by JSummersAqua** [comment]
Is this still an issue?

**Comment by chukon** [comment]
@duchacz @PKlebs123  see question below. - Chuck
![image](https://user-images.githubusercontent.com/3256516/44030177-9afe07ac-9ec5-11e8-9a74-b7275b002445.png)

**Comment by JSummersAqua** [comment]
Added code to correct this. Changes have been moved to DEV.

**Comment by duchacz** [comment]
Cannot test it.  I went into the test version and bridged proposal 48507, Vantage does not pull any parts in.  Please give me a way to test and I will do so.

**Comment by JSummersAqua** [comment]
Tested and confirmed to work correctly.

[https://app.zenhub.com/files/136026663/c7b16606-ebdb-459f-9b8a-38b26217a0c0/download](https://app.zenhub.com/files/136026663/c7b16606-ebdb-459f-9b8a-38b26217a0c0/download)
