### ISSUE TITLE
SO number not pulling in from vantage

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#36]
SO number not pulling in from vantage. I closed out of project still not working. I entered it in and it did not save

John,

The system locked up twice when trying to generate the project ID # for me. Finally came through and I was able to create a proposal # but received the below error.
![2018-06-05_0819.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/cae24a99-bc69-447b-bf2b-5fe34300c58e)

**Comment by mevillarreal** [comment]
Just FYI - this is a recurring problem - we have opened 3 different orders this morning, and none have pulled the SO#, all are updated to show "Order" status however, and using the update button as John had previously suggested does not work. To confirm Denise's comments, closing out of the system and reopening also showed no improvement.

**Comment by chukon** [comment]
This has been updated to allow the SO# field to be manually updated as it was in Vantage. You can also put multiple SO#'s in field

**Comment by chukon** [comment]
@mevillarreal Are you able to enter multiple SO #'s?

**Comment by mevillarreal** [comment]
This feature is working fine :+1:
