### ISSUE TITLE
Terms comments incorrect on proposal

### ISSUE THREAD

**Issue by duchacz** [aquaaerobic/RP#37]
At the bottom of the page before it lists our terms, the paragraph has shifted and some of the wording is incorrect.  Should read as follows:

Goods quoted above will be sold subject to the terms and conditions of sale set forth on the face hereof and the following pages entitled "Terms and Conditions of Aqua-Aerobic Systems, Inc.": Any different or additional terms are 

![image](https://user-images.githubusercontent.com/39917845/40989970-0db55fe4-68b5-11e8-9f04-5d9d2d617746.png)

**Comment by JSummersAqua** [comment]
Which type of proposal did this happen on? 

Also did this occur in the print preview screen, or after it was saved as a PDF?

**Comment by duchacz** [comment]
This was on the PDF.
