### ISSUE TITLE
Bridging Order to Vantage

### ISSUE THREAD

**Issue by duchacz** [aquaaerobic/RP#40]
After exporting a proposal, when you go to get your opportunity/quote # to create a proposal, the system first tries to pull in a random part number which appears to be a 9 in front of the project ID, see example below.

![image](https://user-images.githubusercontent.com/39917845/41102023-6b3045e0-6a2b-11e8-9c07-f5f461c7a697.png)

When I tried to bridge the quote again, it did pull up the correct parts after a couple tries.

![image](https://user-images.githubusercontent.com/39917845/41102396-6a64d328-6a2c-11e8-8033-703ef17f9ef1.png)

***Chuck, can you please add that pop up box which lets you know when all of the lines from your proposal have actually made it into Vantage?

**Comment by chukon** [comment]
Popup Message and progress bar has been added when exporting proposal to Vantage.

![image.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/1cadae43-3b84-437f-a2c7-52927b52e3cf)
