### ISSUE TITLE
Check all reports for correct SQL connection

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#43]
Found a report **RPProjectSchedule.rpt** with incorrect SQL connection causing login prompt.

![2018-06-11_0652.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/2a589f23-cae0-440b-a853-79723fb48e82)

**Comment by JSummersAqua** [comment]
Double-checked all reports for correct SQL connection.
