### ISSUE TITLE
P04 Project created in Vantage

### ISSUE THREAD

**Issue by duchacz** [aquaaerobic/RP#44]
When searching under "project tracker" in Vantage, you should only be able to pull up the root project and the A,B,C, etc.  I went to search on a project I just put in a parts proposal for and it showed the 114190P04 project listed.  This will junk up our system, we do not want these "projects" showing in the system.

![image](https://user-images.githubusercontent.com/39917845/41248918-11e5cd66-6d78-11e8-9439-75f08c360435.png)

**Comment by chukon** [comment]
Vantage is the source database for all projects so if you do a search by root id you will query all prefixes of that baseid (A,B,C, PO1, PO2, etc.) from RP and APD systems. This cannot be changed. You might be able to do an advanced query to filter out PO#'s.

**Comment by duchacz** [comment]
Chuck, we have never pulled up P02 when searching under project tracker.  If the system showed this, we would have thousands of junk projects (aftermarket does $50 proposals sometimes).  This should not be this way.

**Comment by chukon** [comment]
@duchacz     adding custom dashboard
