### ISSUE TITLE
Proposal address formatting

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#45]
Change address formatting on proposals to proper formatting rather than having address, state, city, zip all on separate lines. 

![oldproposal.JPG](https://images.zenhubusercontent.com/5b1e76c1b7b2d2103d3e9d12/137e1ed2-fcfc-4bc7-92f4-3ca13197c3fe)![newproposal.JPG]
(https://images.zenhubusercontent.com/5b1e76c1b7b2d2103d3e9d12/23150fc1-a1c6-4df2-a535-b10f1abf65a9)

**Comment by chukon** [comment]
@JSummersAqua , how is this going?

**Comment by JSummersAqua** [comment]
This is ready for testing in the Dev version of RP.

**Comment by duchacz** [comment]
Looks good!
