### ISSUE TITLE
RP will not pull up a project

### ISSUE THREAD

**Issue by duchacz** [aquaaerobic/RP#48]
I created oppty/quote# 50093 and choose Project 104564A from the drop down menu in RP when creating the new project.  It then gave me the below error message.

![image](https://user-images.githubusercontent.com/39917845/41312713-640bef0a-6e4d-11e8-9da8-c92c25b204e9.png)

**Comment by duchacz** [comment]
This is the same customer, the system froze on my yesterday when I clicked on the project (104564A).  It looks like the system did something goofy and gave me project 104564A and AP01.  This is definitely something we need to keep an eye on.  It should be deleted from project A and left on AP01.

**Comment by chukon** [comment]
I removed quote from 104564A. Please close.
