### ISSUE TITLE
New RP Dashboard for ProjectID Search on Vantage

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#50]
Chuck,

Can you please create a dashboard for this?  We currently type in the root project such as 102100 under the project ID search and then we have to select all of the projects (A,B,C , etc.) and then we have to arrow through to search each project separetly.  The dashboard would be great because it would list all the projects with the equipment.

Aftermarket uses the Memo button or the “project comments” section to confirm what kind of equipment was sold under the project.  If this information is blank we will go the “orders” tab and search parts.  

![image.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/759d6360-297f-4405-8907-1404e6e3bb12)

**Comment by chukon** [comment]
Ready to test. I will come up to install.

\\aqua26\Neptune\RP\Dashboards\VantageProjectSearch\setup.exe

**Comment by duchacz** [comment]
Chuck, I tried opening the icon on my desktop and it states the following: 

![image](https://user-images.githubusercontent.com/39917845/42511753-5d8a4754-8418-11e8-9eb6-eecd33b0215c.png)

**Comment by mevillarreal** [comment]
I was able to use successfully this AM 
![image](https://user-images.githubusercontent.com/39957843/42575820-ebb90eba-84e6-11e8-9168-34fb2b25db94.png)
