### ISSUE TITLE
Proposal Cutting Off Text and Format Issues

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#51]
Chuck,

When creating a PDF of the proposal done in the system, the layout of the closing notes changed on lines 2 and 3 (even though the RP print screen shows all bullet points are the same format).  It also cut of the “L” under #3 “actual charges to be added to invoice”. 

![image.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/12f70ef9-7867-4ca9-94a0-3dfa6e605314)

![image.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/fb130457-4f67-4159-9e51-5120ecd5c9d2)

**Comment by JSummersAqua** [comment]
Changed the formatting so that all the notes line up. Also changed so that text shouldn't be cut off on the right side.
