### ISSUE TITLE
Error when entering text in special project notes.

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#57]

**Comment by JSummersAqua** [comment]
[https://app.zenhub.com/files/136026663/ccd02b0f-2db9-48be-a8bb-017851899c1d/download](https://app.zenhub.com/files/136026663/ccd02b0f-2db9-48be-a8bb-017851899c1d/download)

**Comment by aquackonkol** [comment]
John, fix in dev and Text me at 8157136321 to roll to live

**Comment by chukon** [comment]
@mevillarreal @JSummersAqua This has been fixed and published to RP Live

**Comment by chukon** [comment]
@mevillarreal is this working for you?
