### ISSUE TITLE
ERROR WHEN TRYING TO OPEN PROPOSAL PART #'S - SEE NULL

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#6]
![2018-06-05_0719](https://user-images.githubusercontent.com/3256516/40975489-ca748ee0-6890-11e8-8313-ebd313b7d1bf.png)

**Comment by mevillarreal** [comment]
We have not encountered this problem this week

**Comment by duchacz** [comment]
I was able to view the part #'s in a proposal, flip through each line, and add a new line with no issues.
