### ISSUE TITLE
Cost Worksheet base cost vs standard cost

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#60]
In the old RP system, the cost worksheet report had boxes at the bottom that showed pricing at Base cost and pricing at Standard cost. It was discovered that when a proposal was entered with a part that had a standard cost of $0.00 it would throw off the calculations on the price worksheet. It was decided to temporarily hide the pricing at Standard cost box.

[https://app.zenhub.com/files/136026663/040b27cf-8979-4070-9b22-315d51031711/download](https://app.zenhub.com/files/136026663/040b27cf-8979-4070-9b22-315d51031711/download)

**Comment by JSummersAqua** [comment]
[https://app.zenhub.com/files/136026663/db071975-65aa-4e7d-a84a-dd95155f7d9f/download](https://app.zenhub.com/files/136026663/db071975-65aa-4e7d-a84a-dd95155f7d9f/download)

**Comment by chukon** [comment]
John, Did you complete this?

**Comment by chukon** [comment]
@JSummersAqua What is the progress of this?

**Comment by JSummersAqua** [comment]
Currently pending. Will likely be a separate project.

**Comment by JSummersAqua** [comment]
This is being handled under issue #81.
