### ISSUE TITLE
Search proposals by part #

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#63]
An option to search all proposals by a part number would be beneficial, even seeing this as a report would help.  This would allow us to see who else was quoted for a specific part and at what price.

**Comment by JSummersAqua** [comment]
Created a dashboard to search all projects/proposals by part number and export results to Excel file.

**Comment by mevillarreal** [comment]
I only see the Project Search Dashboard at this time? or has this not been released yet?

**Comment by JSummersAqua** [comment]
This has not been released yet. We will let you know when it is and the status will be changed to "ready to test".

**Comment by chukon** [comment]
@JSummersAqua Where are we at with this?

**Comment by chukon** [comment]
@JSummersAqua here is the path needed \\aqua26\Neptune\RP\Dashboards\RPPartsSearch\setup.exe

**Comment by JSummersAqua** [comment]
This has been released in the development version of RP.

**Comment by mevillarreal** [comment]
Sorry I realize I posted on the wrong forum..
This works nicely! Brings everything up - will be very useful. However - I attempted to sort by date within the dashboard and got this error
![image](https://user-images.githubusercontent.com/39957843/42885784-8a579fde-8a67-11e8-9cce-3490d902d90c.png)

**Comment by JSummersAqua** [comment]
Added Project ID field.
