### ISSUE TITLE
Lump sum proposal

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#64]
When you choose to show your proposal as a lump sum but also include available options for accessories, the total of the proposal includes the optional parts into the lump sum which throws off the number.  The total should be the sum of only the parts being quoted, any additional accessory options should be excluded from that amount.

**Comment by JSummersAqua** [comment]
This has been corrected. Please test.

**Comment by duchacz** [comment]
John, this is not working.  It is still putting the dollar amount for the optional accessories into the total.

![image](https://user-images.githubusercontent.com/39917845/42511679-2ca3181e-8418-11e8-92a8-9c5a053249c1.png)

**Comment by JSummersAqua** [comment]
Should be corrected now.
