### ISSUE TITLE
Add proposal description to proposal tree

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#65]
![proposals.JPG](https://images.zenhubusercontent.com/5b1e76c1b7b2d2103d3e9d12/9b669459-9dcf-4b5e-8854-e61f55a29a8d)

**Comment by chukon** [comment]
![image](https://user-images.githubusercontent.com/3256516/42511764-63929728-8418-11e8-94e2-46db4ac847fc.png)

**Comment by mevillarreal** [comment]
So far this feature is working well for me :+1:
