### ISSUE TITLE
International Startup/Freight fields greyed out

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#66]
There are a few fields on the international startup/freight tab that are greyed out. They were greyed out in the old RP system as well. Need to research to see if these fields need to be usable.

[https://app.zenhub.com/files/136026663/a50c2057-715f-4f4f-b949-1ef63d2eaeb0/download](https://app.zenhub.com/files/136026663/a50c2057-715f-4f4f-b949-1ef63d2eaeb0/download)

**Comment by chukon** [comment]
@JSummersAqua What is the progress of this?

**Comment by JSummersAqua** [comment]
Code has been added for these fields. Working on adding them to INTL proposal report.
