### ISSUE TITLE
Error when adding part

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#68]
Appears that an error occurs when a part is added with $0 as the cost and the level is set as customsell.

[https://app.zenhub.com/files/136026663/de9d0e03-defa-4dba-bf8a-cd14460bd0ba/download](https://app.zenhub.com/files/136026663/de9d0e03-defa-4dba-bf8a-cd14460bd0ba/download)

**Comment by JSummersAqua** [comment]
Added code to correct this.

**Comment by mevillarreal** [comment]
Have not had this error reoccur as of yet.
