### ISSUE TITLE
Error when accidentally blanking out price level field.

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#69]
Error occurred when user accidentally blanked out price level field.

[https://app.zenhub.com/files/136026663/7b422611-d3ed-4e5a-9d6e-5dbb4aff92c9/download](https://app.zenhub.com/files/136026663/7b422611-d3ed-4e5a-9d6e-5dbb4aff92c9/download)

**Comment by JSummersAqua** [comment]
Changed dropdown to not allow users to manually type into the field.

**Comment by mevillarreal** [comment]
This issue has not reoccurred since last week - thus far
