### ISSUE TITLE
error when creating a PDF (twice)

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#7]
Error creating PDF from Proposal preview.

![2018-06-05_0720.png](https://images.zenhubusercontent.com/58f8cc1051aa2c30577bf686/6db4a30a-53fb-4699-b8a7-d1c64b2d1207)

**Comment by mevillarreal** [comment]
As of recently - this feature has been working correctly so long as we use the "Save As PDF" button, versus printing to the PDF printer.

**Comment by duchacz** [comment]
No issues creating a PDF.
