### ISSUE TITLE
Sort schedule reports by date

### ISSUE THREAD

**Issue by JSummersAqua** [aquaaerobic/RP#72]
Add ability to sort schedule reports by date.

[https://app.zenhub.com/files/136026663/460c5d17-610c-480b-aa33-84a01626ff84/download](https://app.zenhub.com/files/136026663/460c5d17-610c-480b-aa33-84a01626ff84/download)

**Comment by chukon** [comment]
@JSummersAqua What is the progress of this?

**Comment by JSummersAqua** [comment]
Working on copying existing report to a new report that is sorted by date rather than alphabetically by project name.

**Comment by JSummersAqua** [comment]
Two new reports have been created for both Dev and Live. One sorts by date in ascending order and the other in descending order. Changes have been made to the application to add the reports to the toolstrip menu on the main screen.

![schedulereports.JPG](https://images.zenhubusercontent.com/5b1e76c1b7b2d2103d3e9d12/b634c478-3b27-4ed3-93f2-dea0695e4d9d)

**Comment by JSummersAqua** [comment]
Changes have been checked in and are ready to publish.
