### ISSUE TITLE
Add all of the discount levels onto the “pricing level” 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#84]
Hi Chuck,

Can you please add all of the discount levels onto the “pricing level” on the main tab for proposals?  For example, I have a proposal with 40 lines that I am trying to quote at 40/0 but that pricing level is not available on the first page so I have to manually choose this on the drop down for each line.

![image](https://user-images.githubusercontent.com/3256516/44719020-9e6c3a80-aa87-11e8-859f-a89ab8cdcd75.png)

**Comment by mevillarreal** [comment]
This is working thus far

Michaela Villarreal
Sales Assistant

AQUA-AEROBIC SYSTEMS, INC.
6306 N. Alpine Rd.
Loves Park, IL 61111-7655
Ph: 815.639.4472 Fax: 815.654.8623
Email: mvillarreal@aqua-aerobic.com<mailto:mvillarreal@aqua-aerobic.com>
www.aqua-aerobic.com

[aqua-aerobics-metawater]
