### ISSUE TITLE
additional options available in the Pricing Level drop down

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/RP#88]
Chuck,

As we discussed, I would like to have additional options available in the Pricing Level drop down menu in the RP database.  Specifically I would request the addition of price levels for:

32.5% gross margin and 0% commission
27.5% gross margin and 5% commission

Please create those options on the Development side of RP, and let the Denises test it.  Let me know when the programming is complete.  Put the bug under Denise U’s name.  Thanks.

Paul Klebs
Aftermarket Sales Manager
 
Aqua-Aerobic Systems, Inc.
6306 N. Alpine Rd.
Loves Park, IL 61111-7655
Ph: 815-639-4466  Fax 815-654-8258
www.aqua-aerobic.com

**Comment by chukon** [comment]
[Doc1.docx](https://github.com/aquaaerobic/RP/files/2461434/Doc1.docx)

**Comment by chukon** [comment]
Chuck,

Can you please make sure these percentages are available on both the “proposal part #’s” tab and “proposal information” main tab?


Thank you,
Denise Uchacz
Aftermarket Sales Representative

Aqua-Aerobic Systems, Inc.
6306 N. Alpine Rd.
Loves Park, IL 61111-7655
Ph: 815-639-4514  Fax 815-654-2508
www.aqua-aerobic.com

**Comment by JSummersAqua** [comment]
Pricing levels have been added and are ready for testing.

**Comment by JSummersAqua** [comment]
Changes were approved and moved to production.

[https://app.zenhub.com/files/136026663/0a4d2497-39ed-4dbc-bdf0-839d7066a4d7/download](https://app.zenhub.com/files/136026663/0a4d2497-39ed-4dbc-bdf0-839d7066a4d7/download)
